import { addIcons } from 'ionicons';
import {
  arrowForward,
  bookOutline,
  fitnessOutline,
  helpCircleOutline,
  homeOutline,
  medicalOutline,
  nutritionOutline,
  notificationsOutline,
  personCircleOutline,
  personOutline,
  pulseOutline,
  searchOutline,
  settingsOutline,
  shieldCheckmarkOutline,
  shieldOutline,
  walkOutline,
  waterOutline,
  eyeOutline,
  eyeOffOutline,
  moonOutline,
  sunnyOutline,
  globeOutline,
  trashOutline,
  keyOutline,
  closeOutline,
  alertCircleOutline,
  chevronForwardOutline,
  chevronBackOutline,
  checkmarkCircleOutline,
  logOutOutline,
  heartOutline,
  bedOutline,
} from 'ionicons/icons';

export function registerIcons(): void {
  addIcons({
    'arrow-forward': arrowForward,
    'book-outline': bookOutline,
    'fitness-outline': fitnessOutline,
    'help-circle-outline': helpCircleOutline,
    'home-outline': homeOutline,
    'medical-outline': medicalOutline,
    'nutrition-outline': nutritionOutline,
    'notifications-outline': notificationsOutline,
    'person-circle-outline': personCircleOutline,
    'person-outline': personOutline,
    'pulse-outline': pulseOutline,
    'search-outline': searchOutline,
    'settings-outline': settingsOutline,
    'shield-checkmark-outline': shieldCheckmarkOutline,
    'shield-outline': shieldOutline,
    'walk-outline': walkOutline,
    'water-outline': waterOutline,
    'eye-outline': eyeOutline,
    'eye-off-outline': eyeOffOutline,
    'moon-outline': moonOutline,
    'sunny-outline': sunnyOutline,
    'globe-outline': globeOutline,
    'trash-outline': trashOutline,
    'key-outline': keyOutline,
    'close-outline': closeOutline,
    'alert-circle-outline': alertCircleOutline,
    'chevron-forward-outline': chevronForwardOutline,
    'chevron-back-outline': chevronBackOutline,
    'checkmark-circle-outline': checkmarkCircleOutline,
    'log-out-outline': logOutOutline,
    'heart-outline': heartOutline,
    'bed-outline': bedOutline,
  });
}
