import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

export type Language = 'en' | 'id';

@Injectable({
  providedIn: 'root',
})
export class LanguageService {
  private readonly currentLanguageSubject = new BehaviorSubject<Language>('en');
  readonly currentLanguage$ = this.currentLanguageSubject.asObservable();

  get currentLanguage(): Language {
    return this.currentLanguageSubject.value;
  }

  setLanguage(language: Language): void {
    this.currentLanguageSubject.next(language);
  }

  toggleLanguage(): void {
    this.setLanguage(this.currentLanguage === 'en' ? 'id' : 'en');
  }

  t(key: string): string {
    const value = this.translations[this.currentLanguage][key];
    return Array.isArray(value) ? value.join(', ') : (value ?? key);
  }

  tArray(key: string): string[] {
    const value = this.translations[this.currentLanguage][key];
    return Array.isArray(value) ? value : [value ?? key];
  }

  private readonly translations: Record<Language, Record<string, string | string[]>> = {
    en: {
      appTitle: 'KidneyGuard AI',
      heroInsightLabel: 'AI health insights',
      dashboardTitle: 'Your kidney wellness dashboard',
      dashboardSubtitle: 'Preventive insights for a healthier tomorrow.',
      dashboardSummary: 'Personal health summary',
      dashboardToday: 'Today',
      dashboardRisk: 'Stable trend',
      dashboardScore: '92% healthy',
      dashboardHydration: 'Hydration',
      dashboardHeartRate: 'Heart rate',
      dashboardSleep: 'Sleep score',
      quickActions: 'Quick actions',
      dailyReminders: 'Daily reminders',
      remindersWater: 'Drink water now',
      remindersExercise: 'Light walk for 15 mins',
      remindersCheck: 'Review your health checklist',
      insightsTitle: 'Insights',
      insightFluid: 'Fluid balance',
      insightFluidText: 'Hydration is staying on track this week.',
      insightRisk: 'Risk preview',
      insightRiskText: 'No immediate concerns detected from your latest screen.',
      insightActivity: 'Activity trend',
      insightActivityText: 'Movement and recovery remain well balanced.',
      insightCare: 'Care tip',
      insightCareText: 'A short walk after dinner can support your recovery rhythm.',
      screeningTitle: 'CKD risk screening',
      screeningSubtitle: 'Answer a short health questionnaire to understand your risk profile.',
      screeningIntro: 'Complete a short assessment to see your kidney risk.',
      screeningAge: 'Age',
      screeningDiabetes: 'Do you have diabetes?',
      screeningHypertension: 'Do you have hypertension?',
      screeningFamily: 'Family history of kidney disease?',
      screeningSmoking: 'Do you smoke?',
      screeningActivity: 'How many days per week do you exercise?',
      screeningWater: 'How many liters of water do you drink daily?',
      screeningAnalyze: 'Analyze my risk',
      screeningAnalyzing: 'Analyzing...',
      screeningResult: 'Your risk result',
      screeningResultSummary: 'Risk is calculated from hydration, activity, and chronic health conditions.',
      screeningRecommendation: 'Personalized recommendation',
      screeningRecommendationLow: 'Keep your hydration routine steady and maintain light activity regularly.',
      screeningRecommendationModerate: 'Increase exercise, keep blood sugar in check, and monitor blood pressure closely.',
      screeningRecommendationHigh: 'Consult a healthcare professional for further evaluation and next steps.',
      screeningLow: 'Low risk',
      screeningModerate: 'Moderate risk',
      screeningHigh: 'High risk',
      screeningDisclaimer: 'This is a preventive screening and not a medical diagnosis.',
      educationTitle: 'Kidney education',
      educationSubtitle: 'Learn practical ways to protect your kidney health.',
      educationArticle1: 'How to protect your kidneys',
      educationArticle1Text: 'Small daily habits like hydration and balanced meals reduce strain on the kidneys.',
      educationArticle2: 'Understanding CKD basics',
      educationArticle2Text: 'Early awareness can help slow progression and improve long-term quality of life.',
      educationArticle3: 'Healthy diet for kidney wellness',
      educationArticle3Text: 'Choose balanced meals, reduce processed foods, and follow your clinician’s guidance.',
      faqTitle: 'Frequently asked questions',
      faqOne: 'Is this app a diagnosis tool?',
      faqOneAnswer: 'No. It offers preventive screening and education only.',
      faqTwo: 'Who should use it?',
      faqTwoAnswer: 'It is helpful for adults concerned about kidney health and lifestyle habits.',
      profileTitle: 'My profile',
      profileSubtitle: 'Review your information and personalize your reminders.',
      profileName: 'Ariana Putri',
      profileAge: '35 years old',
      profileHistory: 'Diabetes screening history',
      profileHistoryValue: '3 screenings completed',
      profileSettings: 'App settings',
      profileNotifications: 'Daily reminders',
      profileReports: 'Weekly health reports',
      profileLanguage: 'Language',
      saved: 'Saved',
      tabDashboard: 'Dashboard',
      tabScreening: 'Screening',
      tabEducation: 'Education',
      tabProfile: 'Profile',
      actionHydration: 'Log hydration',
      actionReview: 'Review care plan',
      actionAi: 'AI summary',
      actionHydrationText: 'Track daily water intake in seconds.',
      actionReviewText: 'Check your care schedule for the next two days.',
      actionAiText: 'Receive a concise snapshot of your health trends.',
      riskLowText: 'Your pattern is encouraging. Continue with your healthy habits.',
      riskModerateText: 'Your current habits suggest a moderate risk profile. Consider early follow-up.',
      riskHighText: 'A higher risk profile was detected. Please speak with a healthcare professional.',
      recommendationsLow: ['Keep hydrating steadily', 'Maintain your current activity level'],
      recommendationsModerate: ['Increase water intake', 'Reduce salty foods and monitor blood pressure'],
      recommendationsHigh: ['Schedule a clinician review', 'Track symptoms and keep a daily log'],
    },
    id: {
      appTitle: 'KidneyGuard AI',
      heroInsightLabel: 'Wawasan kesehatan berbasis AI',
      dashboardTitle: 'Dasbor kesehatan ginjal Anda',
      dashboardSubtitle: 'Wawasan preventif untuk masa depan yang lebih sehat.',
      dashboardSummary: 'Ringkasan kesehatan pribadi',
      dashboardToday: 'Hari ini',
      dashboardRisk: 'Tren stabil',
      dashboardScore: '92% sehat',
      dashboardHydration: 'Asupan cairan',
      dashboardHeartRate: 'Detak jantung',
      dashboardSleep: 'Skor tidur',
      quickActions: 'Tindakan cepat',
      dailyReminders: 'Pengingat harian',
      remindersWater: 'Minum air sekarang',
      remindersExercise: 'Jalan santai selama 15 menit',
      remindersCheck: 'Tinjau checklist kesehatan Anda',
      insightsTitle: 'Wawasan',
      insightFluid: 'Keseimbangan cairan',
      insightFluidText: 'Asupan cairan tetap terjaga minggu ini.',
      insightRisk: 'Pratinjau risiko',
      insightRiskText: 'Tidak ada kekhawatiran langsung dari pemeriksaan terakhir.',
      insightActivity: 'Tren aktivitas',
      insightActivityText: 'Gerak dan pemulihan tetap seimbang.',
      insightCare: 'Tips perawatan',
      insightCareText: 'Jalan santai setelah makan malam dapat mendukung ritme pemulihan Anda.',
      screeningTitle: 'Skrining risiko CKD',
      screeningSubtitle: 'Jawab kuisioner singkat untuk memahami profil risiko Anda.',
      screeningIntro: 'Lengkapi asesmen singkat untuk melihat risiko ginjal Anda.',
      screeningAge: 'Usia',
      screeningDiabetes: 'Apakah Anda menderita diabetes?',
      screeningHypertension: 'Apakah Anda menderita hipertensi?',
      screeningFamily: 'Riwayat keluarga dengan penyakit ginjal?',
      screeningSmoking: 'Apakah Anda merokok?',
      screeningActivity: 'Berapa kali Anda berolahraga dalam seminggu?',
      screeningWater: 'Berapa liter konsumsi air putih Anda per hari?',
      screeningAnalyze: 'Analisis risiko saya',
      screeningAnalyzing: 'Menganalisis...',
      screeningResult: 'Hasil risiko Anda',
      screeningResultSummary: 'Risiko dihitung dari hidrasi, aktivitas, dan kondisi kesehatan kronis Anda.',
      screeningRecommendation: 'Rekomendasi yang dipersonalisasi',
      screeningRecommendationLow: 'Pertahankan rutinitas air yang baik dan olahraga ringan secara konsisten.',
      screeningRecommendationModerate: 'Tingkatkan olahraga, kontrol gula darah, dan pantau tekanan darah.',
      screeningRecommendationHigh: 'Segera konsultasikan dengan tenaga kesehatan untuk langkah lanjutan.',
      screeningLow: 'Risiko rendah',
      screeningModerate: 'Risiko sedang',
      screeningHigh: 'Risiko tinggi',
      screeningDisclaimer: 'Ini adalah skrining preventif dan bukan diagnosis medis.',
      educationTitle: 'Edukasi ginjal',
      educationSubtitle: 'Pelajari cara praktis untuk melindungi kesehatan ginjal Anda.',
      educationArticle1: 'Cara melindungi ginjal Anda',
      educationArticle1Text: 'Kebiasaan kecil sehari-hari seperti minum cukup air dan makan seimbang mengurangi beban pada ginjal.',
      educationArticle2: 'Memahami dasar CKD',
      educationArticle2Text: 'Kesadaran sejak dini dapat membantu memperlambat perkembangan penyakit dan meningkatkan kualitas hidup.',
      educationArticle3: 'Pola makan sehat untuk kesehatan ginjal',
      educationArticle3Text: 'Pilih makanan seimbang, kurangi makanan olahan, dan ikuti arahan tenaga kesehatan Anda.',
      faqTitle: 'Pertanyaan yang sering diajukan',
      faqOne: 'Apakah aplikasi ini alat diagnosis?',
      faqOneAnswer: 'Tidak. Aplikasi ini hanya menawarkan skrining preventif dan edukasi.',
      faqTwo: 'Siapa yang sebaiknya menggunakannya?',
      faqTwoAnswer: 'Aplikasi ini bermanfaat bagi orang dewasa yang khawatir tentang kesehatan ginjal dan kebiasaan hidup.',
      profileTitle: 'Profil saya',
      profileSubtitle: 'Tinjau informasi Anda dan sesuaikan pengingat Anda.',
      profileName: 'Ariana Putri',
      profileAge: '35 tahun',
      profileHistory: 'Riwayat skrining diabetes',
      profileHistoryValue: '3 skrining selesai',
      profileSettings: 'Pengaturan aplikasi',
      profileNotifications: 'Pengingat harian',
      profileReports: 'Laporan kesehatan mingguan',
      profileLanguage: 'Bahasa',
      saved: 'Tersimpan',
      tabDashboard: 'Beranda',
      tabScreening: 'Skrining',
      tabEducation: 'Edukasi',
      tabProfile: 'Profil',
      actionHydration: 'Catat hidrasi',
      actionReview: 'Tinjau rencana perawatan',
      actionAi: 'Ringkasan AI',
      actionHydrationText: 'Catat asupan air harian dalam hitungan detik.',
      actionReviewText: 'Periksa jadwal perawatan Anda untuk dua hari ke depan.',
      actionAiText: 'Dapatkan gambaran singkat tren kesehatan Anda.',
      riskLowText: 'Pola Anda cukup baik. Lanjutkan kebiasaan sehat Anda.',
      riskModerateText: 'Kebiasaan Anda menunjukkan profil risiko sedang. Pertimbangkan tindak lanjut dini.',
      riskHighText: 'Profil risiko yang lebih tinggi terdeteksi. Silakan konsultasikan dengan tenaga kesehatan.',
      recommendationsLow: ['Tetap minum air secara teratur', 'Pertahankan tingkat aktivitas Anda'],
      recommendationsModerate: ['Tambah asupan air', 'Kurangi makanan asin dan pantau tekanan darah'],
      recommendationsHigh: ['Jadwalkan pemeriksaan klinis', 'Catat gejala dan simpan log harian'],
    },
  };
}
